# Generated by Django 4.1.2 on 2022-10-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, null=True, verbose_name='Фамилия')),
                ('username', models.SlugField(max_length=40, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=40, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Пользователь'), ('moderator', 'Модератор')], default='member', max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('location', models.ManyToManyField(to='user.location')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
        ),
    ]
